name: Close inactive issues

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # WARNING
          days-before-issue-stale: 30
          stale-issue-label: stale
          stale-issue-message: >
            This issue has been inactive for 30 days.
            If there is no further activity, it will be automatically closed after 38 days.

          # CLOSE
          days-before-issue-close: 8
          close-issue-message: >
            This issue was automatically closed after 38 days of inactivity.
